// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 17.0 (Build Build 595 04/25/2017)
// Created on Fri Sep 03 02:56:14 2021

async_transmitter async_transmitter_inst
(
	.clk(clk) ,	// input  clk
	.TxD_start(TxD_start) ,	// input  TxD_start
	.TxD_data(TxD_data) ,	// input [7:0] TxD_data
	.TxD(TxD) ,	// output  TxD
	.TxD_busy(TxD_busy) 	// output  TxD_busy
);

defparam async_transmitter_inst.ClkFrequency = 24000000;
defparam async_transmitter_inst.Baud = 9600;
defparam async_transmitter_inst.RegisterInputData = 1;
defparam async_transmitter_inst.BaudGeneratorAccWidth = 16;
